services:
  postgres:
    image: postgres:latest
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - db_network

  djangoapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    networks:
      - db_network
    depends_on:
      postgres:
        condition: service_healthy

  nuxtapp:
    build:
      context: ./nuxt-app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data:
